export const MOCK_DATA = [
  {
    id: "1",
    code: "PHUONG.BIA.TO.DIE.1",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "2",
    code: "PHUONG.BIA.TO.DIE.2",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "3",
    code: "PHUONG.BIA.TO.DIE.3",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "4",
    code: "PHUONG.BIA.TO.DIE.4",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "5",
    code: "PHUONG.BIA.TO.DIE.5",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "6",
    code: "PHUONG.BIA.TO.DIE.6",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "7",
    code: "PHUONG.BIA.TO.DIE.7",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "8",
    code: "PHUONG.BIA.TO.DIE.8",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "9",
    code: "PHUONG.BIA.TO.DIE.9",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "10",
    code: "PHUONG.BIA.TO.DIE.10",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "11",
    code: "PHUONG.BIA.TO.DIE.11",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "12",
    code: "PHUONG.BIA.TO.DIE.12",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "13",
    code: "PHUONG.BIA.TO.DIE.13",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "14",
    code: "PHUONG.BIA.TO.DIE.14",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "15",
    code: "PHUONG.BIA.TO.DIE.15",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "16",
    code: "PHUONG.BIA.TO.DIE.16",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "17",
    code: "PHUONG.BIA.TO.DIE.17",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "18",
    code: "PHUONG.BIA.TO.DIE.18",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "19",
    code: "PHUONG.BIA.TO.DIE.19",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "20",
    code: "PHUONG.BIA.TO.DIE.20",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
  {
    id: "21",
    code: "PHUONG.BIA.TO.DIE.21",
    name: "Phương Phúng Phính béoooo",
    nguoi_de_xuat: "Công ăn nhậu",
    viet_tat: "PPP",
    trang_thai: "Mới tạo",
    ghi_chu: "Ghi chú cho dữ liệu này",
  },
];
